### ISSUE TITLE
Cannot open archive

### ISSUE THREAD

**Issue by ryoppippi** [mattn/zig-update#2]
```
2022/09/12 21:21:54 unsupported archive: https://ziglang.org/builds/zig-macos-aarch64-0.10.0-dev.3986+e323cf126.tar.xz
```
This error comes on my M1/Intel Macs.

I don't know how to fix it, so I report it.

**Comment by ryoppippi** [comment]
@mattn 
It works! Thanks

**Comment by ryoppippi** [comment]
@mattn 
No error occurs, but the directory I would like to install remains empty.

**Comment by mattn** [comment]
Sorry, fixed.

**Comment by ryoppippi** [comment]
Thank you so much!
